### ISSUE TITLE
hide show group VMs tick box when it would have no effect

### ISSUE THREAD

**Issue by GRyall** [stfc/cloud#64]
Not all groups will want to see each others VMs, so having the tick box will just be a source of confusion for users. It would be good if it wasn't visible in this case. The case can be identified by the list of the users VMs being the same length as the one when they see all the ones visible to them. Alternatively, the longer of the lists could be examined for VMs not owned by the user.

**Comment by GooBall** [comment]
To be clear... To avoid confusion, users should only be able to see the tick-box option if they are part of a group that has VMs besides the ones that the individual has created themselves.

I do have a question though. Might a user ever be part of more than 1 group? If so, would it make sense to use a dropdown (instead of a tick-box) with the names of all the groups they are a member of?

This could mean that, if you were not part of a group, you wouldn't be able to select anything other then your own view - thereby removing the need to hide the dropdown/tick-box.

**Comment by GooBall** [comment]
Implemented in #75 and #76
